### ISSUE TITLE
[Isthmus] Convert SQL expression to Substrait `ExtendedExpression`

### ISSUE THREAD

**Issue by ianmcook** [substrait-io/substrait-java#128]
https://github.com/substrait-io/substrait/pull/405 added an `ExtendedExpression` message to represent standalone expressions (expressions that are not part of plans). #127 would add support for this in the Substrait Java library. It would also be nice if Isthmus could convert SQL expressions (not whole queries) to Substrait `ExtendedExpression` messages. This would help to open up more applications for Substrait as an interoperable representation for expressions.

**Comment by danepitkin** [comment]
Looks like we just need to extend https://github.com/substrait-io/substrait-java/blob/main/isthmus/src/main/java/io/substrait/isthmus/SqlToSubstrait.java to work with `ExtendedExpressions`.
