### ISSUE TITLE
Add back task of init substrait submodule to fix build issue.

### ISSUE THREAD

**Issue by jinfengni** [substrait-io/substrait-java#13]
The commit 83abf918c8 removed the submodule init task. As such,  ./gradlew build would fail due to missing source codes in substrait repo.

```
 error: package io.substrait.proto does not exist
import io.substrait.proto.JoinRel;
```

https://github.com/substrait-io/substrait-java/commit/83abf918c8db778551c8b4b8f638db457ba04b28

**Comment by jacques-n** [comment]
@curino , can you pick this up? It looks like your patch accidentally undid some other changes. Thanks!

**Comment by curino** [comment]
Ops sorry about that... Happy to look at it, I had a messy merge and restarted with a clean clone copying the changes  but something must have gone wrong. My week looks busy, if I am too slow and this is blocking others feel free to revert the patch and I will look at it later.

**Comment by nastra** [comment]
I cherry-picked it back with 5a660ad5701ebc7cdec7c4840aac0f34d64822d0
