### ISSUE TITLE
[Isthmus] Specify failure behavior on cast

### ISSUE THREAD

**Issue by westonpace** [substrait-io/substrait-java#134]
The field `Cast::failure_behavior` has no listed default and yet Isthmus does not specify a value which forces consumers to guess.

**Comment by mbwhite** [comment]
Hello - I was just looking at this as it's occurred in some testing I was doing (and had to manually modify the substrait plans to workaround it)

Expressions is created [here ](https://github.com/substrait-io/substrait-java/blob/a1186b3d9cfcbe3faa52f8192ace3ca2a65e9219/isthmus/src/main/java/io/substrait/isthmus/expression/CallConverters.java#L31)

```
  public static Function<TypeConverter, SimpleCallConverter> CAST =
      typeConverter ->
          (call, visitor) -> {
            if (call.getKind() != SqlKind.CAST) {
              return null;
            }

            return ExpressionCreator.cast(
                typeConverter.toSubstrait(call.getType()),
                visitor.apply(call.getOperands().get(0)));

          };
```
Does it make sense to add a field/method on the TypeConverter to specify the error condition?
Extra field needs to be added to the `ExpressionCreate.cast`   - question is where to get this from...

**Comment by westonpace** [comment]
My guess (which could be very wrong given how little I know about isthmus) is that it `call.getKind() == SqlKind.CAST` implies `FAILURE_BEHAVIOR_THROW_EXCEPTION` and `call.getKind() == SqlKind.SAFE_CAST` implies `FAILURE_BEHAVIOR_RETURN_NULL`.  Although, from the snippet you provided, it looks like `SAFE_CAST` isn't being handled here anyways.

**Comment by mbwhite** [comment]
Admit I've not heard of a `SAFE_CAST`  might be the version of calcite-sql I've got.
Would make sense to me to have the default be throw an exception.

**Comment by vbarua** [comment]
TIL about [SqlKind.SAFE_CAST](https://calcite.apache.org/javadocAggregate/org/apache/calcite/sql/SqlKind.html#SAFE_CAST) vs [SqlKind.CAST](https://calcite.apache.org/javadocAggregate/org/apache/calcite/sql/SqlKind.html#CAST). I think Weston has it correct in terms of the mappings.

@mbwhite if you were to make a PR for this I'd be happy to review it.
