### ISSUE TITLE
Does substrait-java core rely on full antlr4 at runtime?

### ISSUE THREAD

**Issue by adamkennedy** [substrait-io/substrait-java#162]
The current substrait core module has a dependency on antlr4 at run-time, which pulls in a lot of extra dependencies in the form of things like the icu library.

Could this be changed to depend on only antlr4-runtime instead?

**Comment by jacques-n** [comment]
We have a relatively simple grammar. I don't think I ever evaluated alternatives. I would expect antlr runtime to work. Want to post a patch trying it out?

**Comment by vbarua** [comment]
Handled in https://github.com/substrait-io/substrait-java/pull/182
