### ISSUE TITLE
Some exceptions are not very informative for the client code

### ISSUE THREAD

**Issue by rkondakov** [substrait-io/substrait-java#221]
Some exceptions in the code do not answer the question "what was wrong" and sometimes it requires debugging to figure out the problem with substrait plan. I propose to add some clarification to several exceptions in the code

**Comment by davisusanibar** [comment]
Hello @rkondakov, could this issue be closed as part of https://github.com/substrait-io/substrait-java/pull/222?

**Comment by rkondakov** [comment]
@davisusanibar yes, it's done. Thanks!
