### ISSUE TITLE
integrate PrecisionTimestamp and PrecisionTimestampTZ into Isthmus

### ISSUE THREAD

**Issue by vbarua** [substrait-io/substrait-java#246]
The changes in https://github.com/substrait-io/substrait-java/pull/247 added POJOs for PrecisionTimestamp and PrecisionTimestampTZ but did not integrate them into Isthmus.

**Comment by ViggoC** [comment]
I'm working on this issue in https://github.com/substrait-io/substrait-java/pull/262, and encountering some problems related to the precision range. There are some precision checks in TypeConverter, eg. decimal and timestamp, but I don't think it's a good idea to hardcode the limit in a converter tool.
