### ISSUE TITLE
Split isthmus into CLI and library components

### ISSUE THREAD

**Issue by bestbeforetoday** [substrait-io/substrait-java#248]
The isthmus component currently contains both library code that is useful to other components, and a CLI command implementation. This means that code that depends on the isthmus component as a library is forced to pull in CLI-specific dependencies, which includes a concrete logging provider (as described in issue #243).

I propose splitting the current content of the isthmus component into two: a library and CLI component. The library component could remain as _isthmus_ since projects likely already depend on that component, or could be renamed to something like _substrait-calcite_. The CLI portion could be named _isthmus-cli_, or could remain as _isthmus_ if the library component used a different name.

**Comment by bestbeforetoday** [comment]
If you agree with this approach, I would be happy to take on this change.

**Comment by vbarua** [comment]
I brought this up in the substrait sync yesterday and the response was generally positive.

In terms of your proposal, I think splitting out the CLI component into `isthmus-cli` and leaving the core package as `isthmus` makes the most sense, as this will minimize the amount of works our downstreams will need to do to migrate.

**Comment by bestbeforetoday** [comment]
Resolved by PR #249 and published in [v0.31.0](https://github.com/substrait-io/substrait-java/releases/tag/v0.31.0).
