### ISSUE TITLE
Remove preview features

### ISSUE THREAD

**Issue by adamkennedy** [substrait-io/substrait-java#4]
As discussed in the PR when it was on the other project, whether we go with Java 17 minimum or something older, either way we should probably not make use of preview features.

**Comment by JamesRTaylor** [comment]
Agreed, @adamkennedy. Do you know of any preview features we're currently using?

**Comment by jacques-n** [comment]
There is only one. We use pattern matching in switches several places I believe: https://openjdk.org/jeps/406

For reference, we may be able to use [jabel](https://github.com/bsideup/jabel) to allow this and still compile to earlier bytecode versions. It only mentions Java 14 in the readme but it seems like work has been merged that supports newer java versions as well.

**Comment by adamkennedy** [comment]
@jacques-n in the mean time, before jabel can handle it and could be set up, would a PR that just rolls back the pattern matching to vanilla Java 17 be accepted.

**Comment by jacques-n** [comment]
Propose it and let's take a look.

**Comment by jacques-n** [comment]
Proposed https://github.com/substrait-io/substrait-java/pull/94

Downgrades to java 11 for jar output

**Comment by jacques-n** [comment]
Resolved with #94
