### ISSUE TITLE
[ISTHMUS] support  order by, limit offset clause in substrait to sql conversion

### ISSUE THREAD

**Issue by jinfengni** [substrait-io/substrait-java#40]
Currently, the converter from substrait rel plan to calcite relnode plan does not support SortRel / FetchRel, and would not produce sql with order by clause, limit offset clause.

This ticket is to track this missing functionality.

**Comment by weijietong** [comment]
I'll work on this.

**Comment by JamesRTaylor** [comment]
Fixed by https://github.com/substrait-io/substrait-java/pull/50
