### ISSUE TITLE
Reflection-based GenericRoundtripTest for ExpressionCreator methods (and failures)

### ISSUE THREAD

**Issue by curino** [substrait-io/substrait-java#5]
(disclaimer this is me poking at the project to learn about it)

I wrote a simple reflection based test, that lists all methods in `ExpressionCreator` and for those using simple types (primitives and things like `Dates` or `BigDecimal` etc). I generate a synthetic set of params and invoke the method doing a roundtrip conversion (lifted from `LiteralRoundtripTest` which was only covering decimal so far). Two questions:

1. Do you agree it makes sense to have something like this in the codebase, to automatically cover (at least a few) cases as they get added to the system? Substrait strikes me as a project that will grow pretty broad and automating high-coverage tests seems worthy. (happy to post code if you agree it makes sense).

2.  I saw several of the methods failing on the roundtrip because the "nullability" seems not retained correctly. Is this by design and we should ignore it in the comparison or is it a bug? (example below with `timestamp` method).
 

```
Invoking timestamp ([boolean, long]) with values ([true, -5750464908882337892])

expected: <TimestampLiteral{nullable=true, value=-5750464908882337892}> but was: <TimestampLiteral{nullable=false, value=-5750464908882337892}>
Expected :TimestampLiteral{nullable=true, value=-5750464908882337892}
Actual   :TimestampLiteral{nullable=false, value=-5750464908882337892}
```

**Comment by JamesRTaylor** [comment]
I think this would be a nice enhancement to improve the code coverage of our tests, @curino. Please feel free to submit a PR. Thanks!

**Comment by curino** [comment]
Hi James, I did the PR and it was merged. The issue should be closed.
