### ISSUE TITLE
[ISTHMUS] Add support for set operations

### ISSUE THREAD

**Issue by JamesRTaylor** [substrait-io/substrait-java#57]
Add support for set operations UNION and MINUS in SQL -> Substrait Proto -> Substrait POJO. This would involve adding implementation of methods in SubstraitRelVisitor, RelCopyOnWriteVisitor, ProtoRelConverter, and RelProtoConverter. Queries such as these should roundtrip between SQL, Substrait Proto, and Substrait POJO:

```
select p_partkey as partkey from part where p_partkey > cast(100 as bigint) 
union select l_partkey as partkey from lineitem where l_orderkey > cast(100 as bigint);
select p_partkey as partkey from part where p_partkey > cast(100 as bigint) 
minus select l_partkey as partkey from lineitem where l_orderkey > cast(100 as bigint);
```

**Comment by guykhazma** [comment]
I am working on a draft PR, will submit it later today or tomorrow
