### ISSUE TITLE
[Isthmus] What's the difference between tpch_smoke.sh and TpchQueryNoValidation

### ISSUE THREAD

**Issue by jikunshang** [substrait-io/substrait-java#81]
I noticed that both of them share almost same code path. `tpch_smoke.sh` can not pass some queries(q7,q8...) while `TpchQueryNoValidation` can pass all. And `tpch_smoke.sh` is in CI workflow, the other one is not.

**Comment by jacques-n** [comment]
They are both in the CI workflow. TpchQueryNoValidation is run as a unit test. tpch_smoke is run against the native compiled binary. The former checks functional behavior, the later that the graal compiled code works (it isn't guaranteed given how graal is a partial jvm).

**Comment by jikunshang** [comment]
Thanks for your explanations @jacques-n !
So current status is:
1. Graal compiled code can not pass all tpch queries(like q7). if so, is there any plan to fix it?
2. If I want to use Isthmus as a binary for functionality, I would better compile/run it in a legacy JVM way.

**Comment by jacques-n** [comment]
> Thanks for your explanations @jacques-n ! So current status is:
> 
> 1. Graal compiled code can not pass all tpch queries(like q7). if so, is there any plan to fix it?

At one point, not all tpch queries were supported. If something is now passing in the no validation test but is failing in graal, please open a ticket.

> 2. If I want to use Isthmus as a binary for functionality, I would better compile/run it in a legacy JVM way.

I don't understand your statement. If you want to use Isthmus as a library in a java project, you can use jars (and ignore graal). If you want to use as a binary executable, you must use graal.

**Comment by jikunshang** [comment]
Got it, thanks again! will submit another issue for failed queries.
